language: node_js
node_js:
- '0.10'
deploy:
  provider: heroku
  api_key:
    secure: Gm/t+CM9dTLtHh77ekzrotkFP4KHQE0b+tlZjuFXdp6EPtnx3L4MtMBhjD2m31tGaJMvqa/p8wBNdgwgIQVimk4b6sgqTTVZmpmz4AllqTu6/GDhbsQdpBygRa6LhjdmgHlmp8sATtMq3SHjY5vFP9sQtCGg8gYwHKnADeTFwtM=
  app: stormy-forest-7328
  on:
    repo: pgremo/market

before_install:
  - npm install -g gulp

script:
  - gulp build --require coffee-script/register